apiVersion: v1
kind: Service
metadata:
  name: pyapp-service
  labels:
    app: cv-app
spec:
  type: LoadBalancer
  selector:
    app: cv-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000  # Must be between 30000 and 32767
---
apiVersion: apps/v1
kind: Deployment  # DEPLOYMENT
metadata:
  name: pyapp-deployment
  labels:
    app: cv-app
spec:  # REPLICA SET
  replicas: 3
  selector:
    matchLabels:
      app: cv-app
  template:
    metadata:
      labels:
        app: cv-app
    spec:  # POD
      containers:
      - name: py-app
        image: cv_app
        imagePullPolicy: Never  # To use local image
        ports:
        - containerPort: 5000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: secret_key
---
